name: "🚀 Feature Request"
description: Propose a new feature for the package
title: "[Feature Request]: "
labels: ["Enhancement", "Feature Request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for making a request. Please provide a clear and concise description of the desired feature.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What functionality would you like to see implemented?
      placeholder: Location in the software, usage, output...
    validations:
      required: true

  - type: textarea
    id: suggestions
    attributes:
      label: Possible Implementation
      description: If you can think of one, describe a possible implementation for the feature.