name: "🙋 Ask a Question"
description: Discuss questions you have about the software
title: "[Question]: "
labels: ["Type: Question"]
body:
  - type: markdown
    attributes:
      value: |
        We are happy to get feedback and help users of our packages. Let's discuss!

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to ask the team?
    validations:
      required: true
