# Assign labels from json definition to all repos
# This uses https://github.com/Financial-Times/github-label-sync

name: Assign labels to all repos

on:  # Runs on any push event in a PR or any push event to master
  push:
    branches:
      - 'issue_redesign'

defaults:
  run:
    shell: bash
    working-directory: ./.github/labels  # labels.json is default filename for github-label-sync
    
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: install github-label-sync
        run: |
          npm install -g github-label-sync
      - name: Assign labels into all repos
        run: |
          github-label-sync pylhc/optics_functions