# Assign labels from json definition to all repos
# This uses https://github.com/Financial-Times/github-label-sync

name: Assign labels to all repos

on:  # Runs on any push event in a PR or any push event to master
  push:
    branches:
      - 'issue_redesign'

defaults:
  run:
    shell: bash
    
jobs:
  assign-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Test the repo
        run: |
          tree

      - name: show current working directory
        run: |
          pwd

      # - name: Install github-label-sync
      #   run: |
      #     npm install -g github-label-sync

      # - name: Assign labels into all repos
      #   working-directory: ./labels  # labels.json is default filename for github-label-sync
      #   run: |
      #     github-label-sync pylhc/optics_functions