# Note -------------------------------------------------------------------------
# For the action used in this workflow to work, the coverage file needs
# to contain relative paths. The only way I found to set this, seems to be
# to add it in your project settings, e.g. in pyproject.toml:

# [tool.coverage.run]
# relative_files = true


# Caller Template --------------------------------------------------------------

# # Runs all tests and runs a coverage report via python-coverage-comment-action.
# name: Coverage

# on:  # Runs on all push events to master branch and any push related to a pull request
#   push:
#     branches:
#       - master
#   pull_request:  # so that codeclimate gets coverage and reports on the diff

# jobs:
#   coverage:
#       uses: pylhc/.github/.github/workflows/coverage.yml@master
#       with:
#         src-dir: omc3
#         pytest-options: -m "not cern_network"
#       secrets: inherit

# ------------------------------------------------------------------------------
name: Reusable Testing with Coverage

on:
  workflow_call:
    inputs:
      src-dir:
        required: true
        type: string
      pytest-options:
        required: false
        type: string
      extra-dependencies:
        required: false
        type: string
        default: test
      dependency-file:
        required: false
        type: string
        default: pyproject.toml
      min_coverage: # minimum overall coverage
        required: false
        type: number
        default: 0.80
      min_diff_coverage: # minimum coverage for the diff in a PR
        required: false
        type: number
        default: 0.60
      allowed_coverage_decrease:  # allowed decrease from reference coverage
        required: false
        type: number
        default: 0.05
      minimum_green:  # If above or equal to this value, the badge will be green.
        required: false
        type: number
        default: 90
      minimum_orange: # If above or equal to this value, the badge will be orange.
        required: false
        type: number
        default: 80

env:
  python-version: "3.13"
  UV_COMPILE_BYTECODE: 1
  ALLOWED_COVERAGE_DECREASE: ${{ inputs.allowed_coverage_decrease }}  # allowed decrease from reference coverage
  MIN_COVERAGE: ${{ inputs.min_coverage }}                            # minimum overall coverage
  MIN_DIFF_COVERAGE: ${{ inputs.min_diff_coverage }}                  # minimum coverage for the diff in a PR
  MINIMUM_GREEN: ${{ inputs.minimum_green }}                          # If above or equal to this value, the badge will be green.
  MINIMUM_ORANGE: ${{ inputs.minimum_orange }}                        # Same with orange. Below is red.

defaults:
  run:
    shell: bash

jobs:
  coverage:
    runs-on: ubuntu-latest
    outputs: # for the check-coverage-* jobs
      reference_percent_covered: ${{ steps.coverage_comment.outputs.reference_percent_covered }}  # coverage ratio of the reference-branch (master)
      new_percent_covered: ${{ steps.coverage_comment.outputs.new_percent_covered }}              # coverage ratio of the current branch (PR)
      diff_total_percent_covered: ${{ steps.coverage_comment.outputs.diff_total_percent_covered }}  # coverage ratio of the files changed in the PR

    steps:
      - uses: actions/checkout@v5

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ env.python-version }}
          enable-cache: true
          activate-environment: true
          cache-dependency-glob: '${{ inputs.dependency-file }}'

      # The uv pip should make & use an env from the Python install of the previous step
      - name: Install package
        run: uv pip install '.[${{ inputs.extra-dependencies }}]'

      - name: Run all tests
        run: python -m pytest ${{ inputs.pytest-options }} --cov=${{ inputs.src-dir }}

      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}

  check-coverage:
    needs: coverage
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Check Coverage Decrease
        env:
           CURRENT_COVERAGE: ${{ needs.coverage.outputs.new_percent_covered }}
           REF_COVERAGE: ${{ needs.coverage.outputs.reference_percent_covered }}
           ALLOWED_COVERAGE_DECREASE: ${{ env.ALLOWED_COVERAGE_DECREASE }}
        run: |
              MIN_COVERAGE_DECR=$(echo "${REF_COVERAGE} - ${ALLOWED_COVERAGE_DECREASE}" | bc)
              echo "Reference Coverage: ${REF_COVERAGE}"
              echo "Current Coverage: ${CURRENT_COVERAGE}"
              echo "Minimum Allowed Coverage (decrease from Reference): ${MIN_COVERAGE_DECR}"
              if (( $(echo "${CURRENT_COVERAGE} < ${MIN_COVERAGE_DECR}" | bc -l) )); then
                echo "Failed: Coverage decreased more than allowed (${CURRENT_COVERAGE} < ${MIN_COVERAGE_DECR})."
                exit 1
              fi
              echo "Success: Coverage decrease is within allowed range!"

      - name: Check Total Coverage
        env:
           CURRENT_COVERAGE: ${{ needs.coverage.outputs.new_percent_covered }}
        run: |
              echo "Current Coverage: ${CURRENT_COVERAGE}"
              echo "Minimum Allowed Coverage: ${MIN_COVERAGE}"
              if (( $(echo "${CURRENT_COVERAGE} < ${MIN_COVERAGE}" | bc -l) )); then
                echo "Failed: Coverage is below minimum (${CURRENT_COVERAGE} < ${MIN_COVERAGE})."
                exit 1
              fi
              echo "Success: Coverage meets minimum requirement!"

      - name: Check Diff Coverage
        env:
            CURRENT_DIFF_COVERAGE: ${{ needs.coverage.outputs.diff_total_percent_covered }}
        run: |
              echo "Current Diff Coverage: ${CURRENT_DIFF_COVERAGE}"
              echo "Minimum Allowed Diff Coverage: ${MIN_DIFF_COVERAGE}"
              if (( $(echo "${CURRENT_DIFF_COVERAGE} < ${MIN_DIFF_COVERAGE}" | bc -l) )); then
                echo "Failed: Diff coverage is below minimum (${CURRENT_DIFF_COVERAGE} < ${MIN_DIFF_COVERAGE})."
                exit 1
              fi
              echo "Success: Diff coverage meets minimum requirement!"
