# Caller Template --------------------------------------------------------------

# # Runs all tests on master on Mondays at 3 am (UTC time)
# name: Cron Testing


# on:
#   schedule:
#     - cron:  '* 3 * * mon'

# jobs:
#     tests:
#       uses: pylhc/.github/.github/workflows/cron.yml@master
#       with:
#         pytest-options: -m "not cern_network"

# ------------------------------------------------------------------------------
name: Reusable Cron-Testing

on:
  workflow_call:
    inputs:
      pytest-options:
        required: false
        type: string
      extra-dependencies:
        required: false
        type: string
        default: test
      dependency-file:
        required: false
        type: string
        default: pyproject.toml

# We use uv pip and it should use the system python from our runner
env:
  UV_SYSTEM_PYTHON: 1

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, macos-latest, windows-latest]
        # We escape with quotes so it doesn't get interpreted as float (e.g. 3.10 -> 3.1 by GA's parser)
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.x"]  # crons should always run latest python hence 3.x

    steps:
      - uses: actions/checkout@v4

      - if: matrix.os == 'macos-latest'
        name: Set up hdf5
        run: brew install hdf5

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: '${{ inputs.dependency-file }}'

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: '**/${{ inputs.dependency-file }}'

      - name: Install package
        run: uv pip install '.[${{ inputs.extra-dependencies }}]'

      - name: Run Tests
        run: python -m pytest ${{ inputs.pytest-options }}
