# Caller Template --------------------------------------------------------------

# # Build documentation
# # The build is uploaded as artifact if the triggering event is a push for a pull request
# # The build is published to github pages if the triggering event is a push to the master branch (PR merge)
# name: Build and upload documentation

# on:  # Runs on any push event in a PR or any push event to master
#   pull_request:
#   push:
#     branches:
#       - 'master'

# jobs:
#   documentation:
#         uses: pylhc/.github/.github/workflows/documentation.yml@master

# ------------------------------------------------------------------------------
name: Reusable Build-Documentation

on:
  workflow_call:
    inputs:
      extra-dependencies:
        required: false
        type: string
        default: doc
      dependency-file:
        required: false
        type: string
        default: pyproject.toml

defaults:
  run:
    shell: bash

jobs:
  documentation:
    runs-on: ubuntu-latest
    env:
        python-version: "3.13"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ env.python-version }}
          enable-cache: true
          cache-dependency-glob: '${{ inputs.dependency-file }}'

      # The uv pip should make & use an env from the Python install of the previous step
      - name: Install package
        run: uv pip install '.[${{ inputs.extra-dependencies }}]'

      - name: Build documentation
        run: python -m sphinx -b html doc ./doc_build -d ./doc_build

      - name: Upload build artifacts  # upload artifacts so reviewers can have a quick look without building documentation from the branch locally
        uses: actions/upload-artifact@v4
        if: success() && github.event_name == 'pull_request'  # only for pushes in PR
        with:
          name: site-build
          path: doc_build
          retention-days: 5

      - name: Upload documentation to gh-pages
        if: success() && github.ref == 'refs/heads/master'  # only for pushes to master
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: doc_build
