# Caller Template --------------------------------------------------------------

# # Publishes to PyPI upon creation of a release
# name: Upload Package to PyPI

# on:  # Runs everytime a release is added to the repository
#   release:
#     types: [created]

# jobs:
#   deploy:
#     uses: pylhc/.github/.github/workflows/publish.yml@master
#     secrets: inherit

# ------------------------------------------------------------------------------
name: Reusable PyPI Upload

on:
  workflow_call:
    inputs:
      dependency-file:
        required: false
        type: string
        default: pyproject.toml
    secrets:
        PYPI_USERNAME:
            required: true
        PYPI_PASSWORD:
            required: true

defaults:
  run:
    shell: bash

jobs:
  deploy: # only a single supported Python on latest ubuntu
    runs-on: ubuntu-latest
    env:
        python-version: "3.13"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ env.python-version }}
          enable-cache: true
          activate-environment: true
          cache-dependency-glob: '${{ inputs.dependency-file }}'

      - name: Upgrade wheel, build and twine
        run: uv pip install --upgrade wheel build twine

      - name: Build and check build
        run: |
          python -m build
          twine check dist/*

      - name: Publish
        if: ${{ success() }}
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/*
