# Caller Template --------------------------------------------------------------

# # Publishes to PyPI upon creation of a release
# name: Upload Package to PyPI

# on:  # Runs everytime a release is added to the repository
#   release:
#     types: [created]

# jobs:
#   deploy:
#     uses: pylhc/.github/.github/workflows/publish.yml@master
#     secrets: inherit

# ------------------------------------------------------------------------------
name: Reusable PyPI Upload

on:
  workflow_call:
    inputs:
      dependency-file:
        required: false
        type: string
        default: pyproject.toml
    secrets:
        PYPI_USERNAME:
            required: true
        PYPI_PASSWORD:
            required: true

# We use uv pip and it should use the system python from our runner
env:
  UV_SYSTEM_PYTHON: 1

defaults:
  run:
    shell: bash

jobs:
  deploy: # only a single supported Python on latest ubuntu
    runs-on: ubuntu-latest
    env:
        python-version: 3.13

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: '${{ inputs.dependency-file }}'

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python-version }}
          cache: 'pip'
          cache-dependency-path: '**/${{ inputs.dependency-file }}'

      - name: Build and check build
        run: |
          python -m build
          twine check dist/*

      - name: Publish
        if: ${{ success() }}
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/*
